### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by test-framework**

### CODE REVIEW

**Review by vladsavelyev — APPROVED** [review]

**Review by vladsavelyev — APPROVED** [review]

**Review by vladsavelyev — APPROVED** [review]

**Review by vladsavelyev — APPROVED** [review]

**Comment by vladsavelyev** [comment]
@multiqc-bot update changelog

**Comment by test-framework** [comment]
@multiqc-bot update changelog

**Comment by test-framework** [comment]
@multiqc-bot update changelog

**Comment by vladsavelyev** [comment]
@multiqc-bot update changelog

**Comment by vladsavelyev** [comment]
@multiqc-bot update changelog

**Comment by vladsavelyev** [comment]
@multiqc-bot update changelog

**Comment by vladsavelyev** [comment]
changelog

**Pull request closed without merging**
